create table if not exists game (
    id int generated by default as identity primary key,
    name varchar(255) unique not null
);

create table if not exists image (
    id int generated by default as identity primary key,
    url varchar(513) unique not null,
    game_id int references game(id)
);